version: 2.1
jobs:
#  set_env:
#    docker:
#      - image: docker:stable
#    steps:
#      - run: echo "$MY_ENV_FILE" | base64 -d > .env
#      - persist_to_workspace:
#          root: .
#          paths:
#            - .
  build:
    docker:
      - image: openjdk:11
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
    steps:
      - checkout
#      - attach_workspace:
#          at: .
      - run:
          command: |
            sleep 10
            ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: openjdk:11-jre-slim
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: docker compose up -d
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
#      - set_env
      - build:
#          requires:
#            - set_env
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
