version: 2.1
jobs:
  
  build:
    docker:
      - image: openjdk:11
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: demopassword
          MYSQL_USER: demouser
          MYSQL_PASSWORD: demopassword
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - run:
          command: DB_PASSWORD=demopassword DB_USER=demouser DB_NAME=pos ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: openjdk:11-jre-slim
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: demopassword
          MYSQL_USER: demouser
          MYSQL_PASSWORD: demopassword
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: DB_PASSWORD=demopassword DB_USER=demouser DB_NAME=pos ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: docker compose up -d
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
