version: 2.1
jobs:

  build:
    docker:
      - image: openjdk:11
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: demopassword
          MYSQL_USER: demouser
          MYSQL_PASSWORD: demopassword
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - run:
          command: DB_HOST=127.0.0.1 DB_PASSWORD=demopassword DB_USER=demouser DB_NAME=pos ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: openjdk:11-jre-slim
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: demopassword
          MYSQL_USER: demouser
          MYSQL_PASSWORD: demopassword
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: DB_HOST=127.0.0.1 DB_PASSWORD=demopassword DB_USER=demouser DB_NAME=pos ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_and_push:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            echo "$MY_CREDS_FILE" | base64 -d > credentials.json 
            gcloud auth activate-service-account --key-file=credentials.json
            gcloud auth configure-docker -q
            docker build -t "asia.gcr.io/dummy-project-365407/pos" .
            docker push "asia.gcr.io/dummy-project-365407/pos"
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          command: |
            echo "$MY_GCE_CREDS_FILE" | base64 -d > credentials.json
            gcloud auth activate-service-account --key-file=credentials.json
            gcloud compute instance-groups managed rolling-action start-update pos-group --version template=pos-instance-template --project dummy-project-365407 --region us-west2
      - persist_to_workspace:
          root: .
          paths:
            - .


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - build_and_push:
          requires:
            - tests
      - deploy:
          requires:
            - build_and_push
