version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:11
      - image: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - run:
          command: ./gradlew build 
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: openjdk:11-jre-slim
      - image: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: ubuntu

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Docker Compose And Exec
          environment:
            COMPOSE_VERSION: '2.12.0'
          command: |
            apt-get update
            apt install  ca-certificates curl gnupg lsb-release apt-utils -y
            mkdir -p /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" |  tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            service docker status
            dockerd
            docker compose -f docker-compose.yml up
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
