version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:11
      - image: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - run:
          command: ./gradlew build 
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: openjdk:11-jre-slim
      - image: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: debian

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Docker Compose And Exec
          environment:
            COMPOSE_VERSION: '2.12.0'
          command: |
            apt-get update && apt-get install curl -y && apt-get install docker -y
            service docker start
            curl -L "https://github.com/docker/compose/releases/download/v${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            /etc/init.d/docker start
            docker-compose -f docker-compose.yml up
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
