version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:11
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
    steps:
      - checkout
      - run:
          command: SPRING_APPLICATION_JSON='{"spring":{"datasource":{"username":${DB_USER},"password":${DB_PASSWORD},"url":"jdbc:mysql://127.0.0.1:3306/"+${DB_NAME}}}}' ./gradlew build
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: openjdk:11-jre-slim
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: docker compose up -d
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
