version: 2.1
jobs:
  build:
    docker:
      - image: openjdk:11
      - image: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - run:
          command: ./gradlew build 
      - persist_to_workspace:
          root: .
          paths:
            - .

  tests:
    docker:
      - image: openjdk:11-jre-slim
      - image: mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: pos
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: ./gradlew test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: docker:stable

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '2.12.0'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          command: docker-compose -f docker-compose.yml up
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
